INSERT INTO TB_BASEUSER (EMAIL, NAME) VALUES ('testeadmin@gmail.com', 'admin teste');
INSERT INTO TB_ADMIN    (PHONE_NUMBER, USERBASE_ID ) VALUES ('(15)996444449', 1);

INSERT INTO TB_BASEUSER (EMAIL, NAME) VALUES ('testeadmin2@gmail.com', 'admin teste2');
INSERT INTO TB_ADMIN    (PHONE_NUMBER, USERBASE_ID ) VALUES ('(15)996444449', 2);



INSERT INTO TB_BASEUSER (EMAIL, NAME) VALUES ('testeattend@gmail.com', 'attends teste');
INSERT INTO TB_ATTEND   (BALANCE, USERBASE_ID ) VALUES (0.00, 3);

INSERT INTO TB_BASEUSER (EMAIL, NAME) VALUES ('testeattend@gmail.com', 'attends teste2');
INSERT INTO TB_ATTEND   (BALANCE, USERBASE_ID ) VALUES (0.00, 4);



INSERT INTO TB_PLACE    (ADDRESS, NAME) VALUES ('Rua X', 'Chacara x');
INSERT INTO TB_PLACE    (ADDRESS, NAME) VALUES ('Rua Y', 'Chacara y');
INSERT INTO TB_PLACE    (ADDRESS, NAME) VALUES ('Rua Z', 'Chacara z');



INSERT INTO TB_EVENT    (AMOUNT_FREE_TICKETS, AMOUNT_PAYED_TICKETS, DESCRIPTION, EMAIL_CONTACT, END_DATE, END_TIME, FREE_TICKECTS_SELLED, NAME, PAYED_TICKECTS_SELLED, PRICE_TICKET, START_DATE, START_TIME, ADMIN_USERBASE_ID) VALUES
                        (50, 150, 'festa da feijuca', 'festatest@gmail.com', '2021-05-25', '23:59', 0, 'feijuca', 0, 150.00, '2021-05-22', '19:00', 1);

INSERT INTO TB_EVENT    (AMOUNT_FREE_TICKETS, AMOUNT_PAYED_TICKETS, DESCRIPTION, EMAIL_CONTACT, END_DATE, END_TIME, FREE_TICKECTS_SELLED, NAME, PAYED_TICKECTS_SELLED, PRICE_TICKET, START_DATE, START_TIME, ADMIN_USERBASE_ID) VALUES                        
                        (20, 100, 'niver da vi', 'festatest@gmail.com', '2021-05-30', '23:59', 0, 'feijuca', 0, 100.00, '2021-05-26', '17:00', 2);


INSERT INTO TB_EVENT_PLACES (EVENTS_ID, PLACES_ID) VALUES (1, 2);
INSERT INTO TB_EVENT_PLACES (EVENTS_ID, PLACES_ID) VALUES (2, 3);    




